---
# Install teleport

- name: Log Bash configuration
  debug:
    msg: About to begin bash configuration

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Curl Route Instalation
  command: curl https://deb.releases.teleport.dev/teleport-pubkey.asc -o {{archive-keyring}}

- name: Creation of teleport.list
  become: true
  tags: addfile
  file: 
     path: '{{teleportlist-route}}'
     state: touch

- name: Insert route on teleport.list
  become: true
  tags: adddata
  lineinfile:
     path: '{{teleportlist-route}}'
     line: "deb [signed-by={{archive-keyring}}] https://deb.releases.teleport.dev/ stable main"
     state: present
     backup: yes

     register: addTeleport

- name: Update APT package
  become: true
  apt:
    update_cache: yes

- name: Python3-dnf Instalation
  become: true
  command: apt install python3-dnf

- name: Teleport Install
  become: true
  command: apt-get install teleport